from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.core.validators
from datetime import date


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]
    operations = [
        migrations.CreateModel('Doctor', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('name', models.CharField(max_length=200)),
            ('specialization', models.CharField(max_length=50, choices=[
                ('general','General Physician'),('cardiology','Cardiology'),('neurology','Neurology'),
                ('orthopedics','Orthopedics'),('pediatrics','Pediatrics'),('dermatology','Dermatology'),
                ('gynecology','Gynecology & Obstetrics'),('psychiatry','Psychiatry'),
                ('ophthalmology','Ophthalmology'),('ent','ENT'),('oncology','Oncology'),
                ('radiology','Radiology'),('urology','Urology'),('nephrology','Nephrology'),
                ('gastroenterology','Gastroenterology'),('endocrinology','Endocrinology'),
                ('pulmonology','Pulmonology'),('rheumatology','Rheumatology'),
            ])),
            ('license_number', models.CharField(max_length=50, unique=True)),
            ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex=r'^\d{10}$', message='Phone number must be exactly 10 digits.')])),
            ('email', models.EmailField(unique=True)),
            ('qualification', models.CharField(max_length=300)),
            ('experience_years', models.PositiveIntegerField(default=0)),
            ('consultation_fee', models.DecimalField(max_digits=8, decimal_places=2, default=500.00)),
            ('available_days', models.CharField(max_length=200, default='Mon,Tue,Wed,Thu,Fri')),
            ('slot_duration_minutes', models.PositiveIntegerField(default=15)),
            ('morning_start', models.TimeField(null=True, blank=True)),
            ('morning_end', models.TimeField(null=True, blank=True)),
            ('evening_start', models.TimeField(null=True, blank=True)),
            ('evening_end', models.TimeField(null=True, blank=True)),
            ('is_available', models.BooleanField(default=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('user', models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='auth.user')),
        ], options={'ordering': ['name']}),

        migrations.CreateModel('Patient', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('patient_id', models.CharField(max_length=20, unique=True, blank=True)),
            ('name', models.CharField(max_length=200)),
            ('date_of_birth', models.DateField()),
            ('gender', models.CharField(max_length=1, choices=[('M','Male'),('F','Female'),('O','Other')])),
            ('marital_status', models.CharField(max_length=10, blank=True, choices=[('single','Single'),('married','Married'),('divorced','Divorced'),('widowed','Widowed')])),
            ('blood_group', models.CharField(max_length=3, blank=True, choices=[('A+','A+'),('A-','A-'),('B+','B+'),('B-','B-'),('O+','O+'),('O-','O-'),('AB+','AB+'),('AB-','AB-')])),
            ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex=r'^\d{10}$')])),
            ('alternate_phone', models.CharField(max_length=10, blank=True, validators=[django.core.validators.RegexValidator(regex=r'^\d{10}$')])),
            ('email', models.EmailField(blank=True)),
            ('address', models.TextField()),
            ('city', models.CharField(max_length=100, blank=True)),
            ('pincode', models.CharField(max_length=6, blank=True)),
            ('occupation', models.CharField(max_length=100, blank=True)),
            ('emergency_contact_name', models.CharField(max_length=200)),
            ('emergency_contact_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex=r'^\d{10}$')])),
            ('emergency_contact_relation', models.CharField(max_length=50, blank=True)),
            ('allergies', models.TextField(blank=True)),
            ('chronic_conditions', models.TextField(blank=True)),
            ('current_medications', models.TextField(blank=True)),
            ('past_surgeries', models.TextField(blank=True)),
            ('family_history', models.TextField(blank=True)),
            ('insurance_provider', models.CharField(max_length=200, blank=True)),
            ('insurance_number', models.CharField(max_length=100, blank=True)),
            ('insurance_validity', models.DateField(null=True, blank=True)),
            ('registered_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('registered_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='auth.user')),
        ], options={'ordering': ['-registered_at']}),

        migrations.CreateModel('Appointment', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('appointment_date', models.DateField()),
            ('appointment_time', models.TimeField()),
            ('appointment_type', models.CharField(max_length=20, default='opd', choices=[('opd','OPD Consultation'),('follow_up','Follow-up'),('emergency','Emergency'),('procedure','Procedure'),('teleconsult','Teleconsultation')])),
            ('status', models.CharField(max_length=20, default='scheduled', choices=[('scheduled','Scheduled'),('confirmed','Confirmed'),('in_progress','In Progress'),('completed','Completed'),('cancelled','Cancelled'),('no_show','No Show')])),
            ('reason', models.TextField()),
            ('notes', models.TextField(blank=True)),
            ('token_number', models.PositiveIntegerField(null=True, blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
            ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor')),
            ('booked_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointments', to='auth.user')),
        ], options={'ordering': ['-appointment_date', 'appointment_time']}),

        migrations.CreateModel('VitalSigns', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ('weight_kg', models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)),
            ('height_cm', models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)),
            ('temperature_f', models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)),
            ('bp_systolic', models.PositiveIntegerField(null=True, blank=True)),
            ('bp_diastolic', models.PositiveIntegerField(null=True, blank=True)),
            ('pulse_bpm', models.PositiveIntegerField(null=True, blank=True)),
            ('spo2_percent', models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)),
            ('respiratory_rate', models.PositiveIntegerField(null=True, blank=True)),
            ('blood_sugar_mgdl', models.DecimalField(max_digits=6, decimal_places=1, null=True, blank=True)),
            ('notes', models.TextField(blank=True)),
            ('appointment', models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.appointment')),
            ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.patient')),
            ('recorded_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to='auth.user')),
        ], options={'ordering': ['-recorded_at']}),

        migrations.CreateModel('MedicalRecord', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('visit_date', models.DateField(default=date.today)),
            ('chief_complaint', models.TextField()),
            ('history_of_present_illness', models.TextField(blank=True)),
            ('examination_findings', models.TextField(blank=True)),
            ('diagnosis', models.TextField()),
            ('icd_code', models.CharField(max_length=20, blank=True)),
            ('treatment_plan', models.TextField()),
            ('lab_tests_ordered', models.TextField(blank=True)),
            ('follow_up_date', models.DateField(null=True, blank=True)),
            ('follow_up_notes', models.TextField(blank=True)),
            ('is_confidential', models.BooleanField(default=False)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.patient')),
            ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.doctor')),
            ('appointment', models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='core.appointment')),
        ], options={'ordering': ['-visit_date']}),

        migrations.CreateModel('Prescription', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('prescribed_date', models.DateField(default=date.today)),
            ('valid_until', models.DateField(null=True, blank=True)),
            ('status', models.CharField(max_length=20, default='active', choices=[('active','Active'),('dispensed','Dispensed'),('completed','Completed'),('cancelled','Cancelled')])),
            ('dispensed_at', models.DateTimeField(null=True, blank=True)),
            ('notes', models.TextField(blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.medicalrecord')),
            ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.patient')),
            ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.doctor')),
            ('dispensed_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='auth.user')),
        ], options={'ordering': ['-prescribed_date']}),

        migrations.CreateModel('PrescriptionItem', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('medicine_name', models.CharField(max_length=200)),
            ('generic_name', models.CharField(max_length=200, blank=True)),
            ('dosage', models.CharField(max_length=100)),
            ('route', models.CharField(max_length=20, default='oral', choices=[('oral','Oral'),('iv','IV'),('im','IM'),('sc','SC'),('topical','Topical'),('inhaled','Inhaled'),('sublingual','Sublingual'),('nasal','Nasal'),('ophthalmic','Ophthalmic')])),
            ('frequency', models.CharField(max_length=20, choices=[('once_daily','Once Daily (OD)'),('twice_daily','Twice Daily (BD)'),('thrice_daily','Thrice Daily (TDS)'),('four_times','Four Times (QID)'),('every_6h','Every 6 Hours'),('every_8h','Every 8 Hours'),('every_12h','Every 12 Hours'),('as_needed','As Needed (SOS)'),('weekly','Weekly'),('alternate_day','Alternate Day'),('stat','Immediately (STAT)')])),
            ('timing', models.CharField(max_length=20, blank=True, choices=[('before_food','Before Food'),('after_food','After Food'),('with_food','With Food'),('bedtime','At Bedtime'),('empty_stomach','Empty Stomach'),('morning','Morning'),('evening','Evening')])),
            ('duration_days', models.PositiveIntegerField()),
            ('quantity', models.PositiveIntegerField(default=1)),
            ('instructions', models.TextField(blank=True)),
            ('is_dispensed', models.BooleanField(default=False)),
            ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.prescription')),
        ]),

        migrations.CreateModel('Bill', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('bill_number', models.CharField(max_length=20, unique=True, blank=True)),
            ('bill_date', models.DateField(default=date.today)),
            ('consultation_charge', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
            ('procedure_charge', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
            ('medicine_charge', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
            ('lab_charge', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
            ('room_charge', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
            ('other_charge', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
            ('other_charge_label', models.CharField(max_length=100, blank=True)),
            ('discount_percent', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
            ('discount_reason', models.CharField(max_length=200, blank=True)),
            ('tax_percent', models.DecimalField(max_digits=5, decimal_places=2, default=0)),
            ('payment_status', models.CharField(max_length=10, default='unpaid', choices=[('unpaid','Unpaid'),('partial','Partially Paid'),('paid','Paid'),('waived','Waived'),('refunded','Refunded')])),
            ('payment_method', models.CharField(max_length=20, blank=True, choices=[('cash','Cash'),('card','Debit/Credit Card'),('upi','UPI'),('netbanking','Net Banking'),('insurance','Insurance'),('cheque','Cheque')])),
            ('amount_paid', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
            ('paid_at', models.DateTimeField(null=True, blank=True)),
            ('notes', models.TextField(blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.patient')),
            ('appointment', models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='core.appointment')),
            ('generated_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to='auth.user')),
        ], options={'ordering': ['-bill_date', '-created_at']}),

        migrations.CreateModel('Payment', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('amount', models.DecimalField(max_digits=10, decimal_places=2)),
            ('payment_method', models.CharField(max_length=20, choices=[('cash','Cash'),('card','Debit/Credit Card'),('upi','UPI'),('netbanking','Net Banking'),('insurance','Insurance'),('cheque','Cheque')])),
            ('transaction_id', models.CharField(max_length=100, blank=True)),
            ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
            ('notes', models.CharField(max_length=200, blank=True)),
            ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.bill')),
            ('received_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='auth.user')),
        ], options={'ordering': ['-paid_at']}),

        migrations.CreateModel('UserProfile', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('role', models.CharField(max_length=20, default='receptionist', choices=[('admin','Administrator'),('doctor','Doctor'),('receptionist','Receptionist'),('pharmacist','Pharmacist'),('nurse','Nurse')])),
            ('phone', models.CharField(max_length=10, blank=True, validators=[django.core.validators.RegexValidator(regex=r'^\d{10}$')])),
            ('is_active_staff', models.BooleanField(default=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
        ]),

        migrations.CreateModel('Notification', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ('title', models.CharField(max_length=200)),
            ('message', models.TextField()),
            ('notif_type', models.CharField(max_length=20, default='system', choices=[('appointment','Appointment'),('billing','Billing'),('record','Medical Record'),('prescription','Prescription'),('system','System')])),
            ('link', models.CharField(max_length=200, blank=True)),
            ('is_read', models.BooleanField(default=False)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auth.user')),
        ], options={'ordering': ['-created_at']}),
    ]
